/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package my.plugin;
import org.apache.jmeter.protocol.http.control.CacheManager;
import org.apache.jmeter.protocol.http.gui.CacheManagerGui;
import org.apache.jmeter.testelement.TestElement;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class LibraryGui extends CacheManagerGui {
    private static final Logger log =
            LoggerFactory.getLogger(LibraryGui.class);

    @Override
    public String getLabelResource() {
//        return "My CacheManager";
        return null;
    }

    @Override
    public String getStaticLabel() {
        return "My CacheManager";
    }

    @Override
    public TestElement createTestElement() {
        CacheManager element = new Library();
        modifyTestElement(element);
        return element;
    }}
